title: Arup Chauhan's Digital Domain
description: Bridging Passions With Technology
baseurl: ""
url: "https://arup-chauhan.github.io"
remote_theme: vszhub/not-pure-poole

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

author:
  name: "Arup Chauhan"
  email: "achauhan4@hawk.iit.edu"
  social:
    github: "https://github.com/Arup-Chauhan"
    linkedin: "https://linkedin.com/in/arupchauhan"
    avatar: "assets/images/avatar.jpg"
